server:
  port: 8086
spring:
  application:
    name: sms-service
  redis:
    host: 192.168.127.200
  rabbitmq:
    host: 192.168.127.200
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyId:  # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName:  # 签名名称
    verifyCodeTemplate:  # 模板名称