server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  ignored-services:
    - upload-service # 忽略upload-service服务
  add-host-header: true # 添加host头信息
  sensitive-headers:
ribbon:
  ConnectTimeout: 5000 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长 (1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout
ly:
  jwt:
    pubKeyPath: D:\app\Java\projects\leyou\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item